// ================================================================
//  langues.js — Traductions centralisées
//  Utilisé par : SiteViewer.vue  et  Saasgenerator.vue
//
//  Codes langues : fr | en | es | ar
//  Export :
//    - translations  → objet complet (pour Saasgenerator)
//    - svTranslations → sous-ensemble SiteViewer (buy, login…)
//    - langs         → liste des langues disponibles
//    - svLangs       → liste avec flags (pour SiteViewer)
// ================================================================

// ── Liste des langues ─────────────────────────────────────────────
export const langs = [
  { code: "fr", label: "🇫🇷 Français" },
  { code: "en", label: "🇬🇧 English"  },
  { code: "es", label: "🇪🇸 Español"  },
  { code: "ar", label: "🇲🇦 العربية"  },
]

export const svLangs = [
  { code: "fr", flag: "🇫🇷", full: "Français" },
  { code: "en", flag: "🇬🇧", full: "English"  },
  { code: "ar", flag: "🇲🇦", full: "العربية"  },
  { code: "es", flag: "🇪🇸", full: "Español"  },
]

// ── Traductions complètes (Saasgenerator + SiteViewer fusionnés) ──
export const translations = {
  fr: {
    // ── Saasgenerator UI ──────────────────────────────────────
    save: "Sauvegarder", saving: "Sauvegarde...", notConnected: "Non connecté",
    saved: "✓ Sauvegardé", unsaved: "● Non sauvegardé",
    edit: "✏ Éditer", preview: "▶ Aperçu",
    sections: "Sections", style: "Style",
    addSection: "Ajouter une section",
    properties: "Propriétés", typography: "Typographie",
    textColor: "Couleur texte", sectionBg: "Fond de section",
    fontSize: "Taille de police", auto: "Auto",
    small: "Petite", normal: "Normale", large: "Grande", xlarge: "Très grande",
    pageStyle: "Style de la page", bgColor: "Couleur de fond",
    textColorPage: "Couleur du texte", font: "Police",
    columns: "Colonnes", emptyPage: "Cette page est vide.",
    addSectionHint: "Ajoutez une section depuis le panneau gauche.",
    export: "Exporter", exportTitle: "Exporter le site",
    exportDesc: "Choisissez votre format d'export",
    htmlStatic: "HTML statique", htmlDesc: "Un fichier .html tout-en-un, prêt à héberger.",
    download: "Télécharger", dlDesc: "Téléchargez votre site complet.",
    exportNote: "Les images sont intégrées en base64. Les paiements Stripe/PayPal nécessitent un backend.",
    recommended: "Recommandé", exportSuccess: "Site exporté en HTML ✓",
    publish: "Publier", publishTitle: "Publier votre site",
    publishDesc: "Choisissez une adresse pour votre site",
    siteAddress: "Adresse du site", siteAddressPlaceholder: "mon-site (ex: mon-boutique)",
    domainLink: "Lier un nom de domaine (optionnel)", domainPlaceholder: "ex: www.mondomaine.com",
    publishBtn: "Publier le site", publishSuccess: "Site publié ✓",
    dnsTitle: "Configuration DNS", dnsDesc: "Ajoutez ces enregistrements chez votre registrar :",
    dnsInputTitle: "Saisir vos DNS personnalisés", dnsInputDesc: "Entrez les serveurs DNS fournis par votre registrar (ex: Godaddy, Namecheap...)",
    dnsNs1: "Serveur DNS 1 (NS1)", dnsNs2: "Serveur DNS 2 (NS2)",
    dnsNs3: "Serveur DNS 3 (optionnel)", dnsNs4: "Serveur DNS 4 (optionnel)",
    saveDns: "Enregistrer les DNS", dnsInstructions: "Instructions",
    dnsStep1: "1. Connectez-vous à votre registrar (GoDaddy, Namecheap, OVH...)",
    dnsStep2: "2. Allez dans la gestion des DNS de votre domaine",
    dnsStep3: "3. Remplacez les NS existants par ceux ci-dessus",
    dnsStep4: "4. La propagation prend 24-48h",
    copyDns: "Copier", dnsCopied: "Copié ✓",
    logoTitle: "Logo du site", logoUpload: "Changer le logo", logoRemove: "Supprimer",
    logoHint: "Cliquez pour ajouter un logo",
    siteNameLabel: "Nom du site", siteNamePlaceholder: "Nom de votre site...",
    configureStripe: "Configurer Stripe", configurePaypal: "Configurer PayPal",
    newPage: "Nouvelle page", keepOnePage: "Gardez au moins une page.",
    connectedError: "Vous devez être connecté.", saveError: "Erreur de sauvegarde.",
    loadError: "Erreur de chargement. Données locales utilisées.",
    paySuccess: "Paiement réussi !", payDone: "Votre paiement a bien été traité.",
    close: "Fermer", cancel: "Annuler", modifyAddress: "Modifier l'adresse",
    cartTitle: "Mon panier", cartEmpty: "Votre panier est vide", cartTotal: "Total",
    cartCheckout: "Finaliser la commande", cartRemove: "Supprimer",
    cartContinue: "Continuer", cartAdd: "Ajouter au panier",
    siteUrlLabel: "URL de votre site",
    publishNoteFile: "Le fichier publier.txt a été téléchargé avec tous les détails.",
    // Section labels
    sHero: "Titre + CTA", sText: "Paragraphe libre", sImage: "Photo / illustration",
    sGallery: "Grille d'images", sVideo: "YouTube / Vimeo", sProducts: "Catalogue",
    sFeatures: "Grille avantages", sPayment: "Stripe & PayPal", sForm: "Formulaire", sDivider: "Ligne décorative",
    // Section edit labels
    heroTitlePh: "Titre principal...", heroSubPh: "Sous-titre...", heroCtaPh: "Bouton CTA...",
    textPh: "Votre texte ici...",
    imgUploadHint: "Cliquer pour charger une image", imgChange: "Changer", imgAltPh: "Texte alt...",
    galleryLabel: "Galerie", galleryImages: "image(s)", galleryAdd: "+ Ajouter",
    galleryEmpty: "Aucune image — cliquez sur \"+ Ajouter\"",
    videoLabel: "Vidéo", videoTitlePh: "Titre de la vidéo...", videoUrlPh: "URL YouTube ou Vimeo...",
    videoHint: "Collez une URL YouTube ou Vimeo",
    productsLabel: "Catalogue produits", addProduct: "+ Produit",
    badgePh: "Badge (Nouveau, Promo...)", productNamePh: "Nom du produit",
    productDescPh: "Description courte", productPricePh: "Prix",
    featureTitlePh: "Titre...", featureDescPh: "Description...",
    paymentLabel: "Section Paiement", paymentTitlePh: "Titre du paiement...",
    paymentDescPh: "Description...", paymentAmountPh: "Montant",
    testStripe: "💳 Tester Stripe", testPaypal: "🅿 Tester PayPal",
    contactLabel: "Formulaire de contact", namePh: "Nom complet", emailPh: "Adresse email",
    msgPh: "Votre message...", sendBtn: "Envoyer →",
    fontDefault: "Par défaut", fontGeorgia: "Georgia", fontCourier: "Courier New",
    fontTrebuchet: "Trebuchet", fontVerdana: "Verdana",
    colOption2: "2 colonnes", colOption3: "3 colonnes", colOption4: "4 colonnes",
    // ── SiteViewer UI ─────────────────────────────────────────
    buy: "🛒 Acheter", login: "🔑 Se connecter", logout: "Déconnexion",
    cart: "Mon panier", delivery: "Livraison & Paiement", checkout: "Finaliser la commande",
    back: "← Retour", payCard: "💳 Payer par carte",
    name: "Nom complet *", email: "Email *",
    password: "Mot de passe * (min.6)", confirm: "Confirmer *",
    createAccount: "✨ Créer mon compte", register: "Inscription",
    send: "Envoyer", noOrders: "Aucune commande pour le moment.",
    discover: "Découvrir les produits →", orders: "MES COMMANDES",
    totalSpent: "TOTAL DÉPENSÉ", forgotPwd: "Mot de passe oublié ?",
    resetSent: "Email envoyé !", address: "Adresse", zip: "Code postal",
    city: "Ville", country: "Pays",
    // Formulaire de contact (section form)
    formTitle: "Contactez-nous",
    formNamePh: "Nom complet", formEmailPh: "Email", formMsgPh: "Votre message...",
    formSend: "Envoyer →", formSending: "Envoi en cours...",
    formSuccess: "✅ Message envoyé ! Nous vous répondrons bientôt.",
    formErrRequired: "Veuillez remplir tous les champs.",
    formErrEmail: "Email invalide.",
    formErrSend: "Erreur d'envoi. Réessayez plus tard.",
    // Checkout
    checkoutClient: "👤 Informations client", checkoutDelivery: "📦 Adresse de livraison",
    checkoutSecure: "🔒 Paiement sécurisé via Stripe",
    checkoutPaying: "Redirection Stripe...",
    // Auth modal
    loginTab: "Connexion", registerTab: "Inscription",
    loginBtn: "🔑 Se connecter", createBtn: "✨ Créer mon compte",
    forgotDesc: "Entrez votre email pour recevoir un lien.",
    forgotSendBtn: "📧 Envoyer le lien",
    // Profile
    storeClient: "🛍 Client du store", signOut: "⏻ Se déconnecter",
    // Payment section
    payWithStripe: "💳 Payer avec Stripe", payWithPaypal: "🅿 Payer avec PayPal",
  },

  en: {
    save: "Save", saving: "Saving...", notConnected: "Not connected",
    saved: "✓ Saved", unsaved: "● Unsaved",
    edit: "✏ Edit", preview: "▶ Preview",
    sections: "Sections", style: "Style",
    addSection: "Add a section",
    properties: "Properties", typography: "Typography",
    textColor: "Text color", sectionBg: "Section background",
    fontSize: "Font size", auto: "Auto",
    small: "Small", normal: "Normal", large: "Large", xlarge: "Extra large",
    pageStyle: "Page style", bgColor: "Background color",
    textColorPage: "Text color", font: "Font",
    columns: "Columns", emptyPage: "This page is empty.",
    addSectionHint: "Add a section from the left panel.",
    export: "Export", exportTitle: "Export site",
    exportDesc: "Choose your export format",
    htmlStatic: "Static HTML", htmlDesc: "A single all-in-one .html file, ready to host.",
    download: "Download", dlDesc: "Download your complete site.",
    exportNote: "Images are embedded in base64. Stripe/PayPal payments require a backend.",
    recommended: "Recommended", exportSuccess: "Site exported as HTML ✓",
    publish: "Publish", publishTitle: "Publish your site",
    publishDesc: "Choose an address for your site",
    siteAddress: "Site address", siteAddressPlaceholder: "my-site (e.g. my-shop)",
    domainLink: "Link a domain name (optional)", domainPlaceholder: "e.g. www.mydomain.com",
    publishBtn: "Publish site", publishSuccess: "Site published ✓",
    dnsTitle: "DNS Configuration", dnsDesc: "Add these records at your registrar:",
    dnsInputTitle: "Enter your custom DNS", dnsInputDesc: "Enter the DNS servers provided by your registrar (e.g. GoDaddy, Namecheap...)",
    dnsNs1: "DNS Server 1 (NS1)", dnsNs2: "DNS Server 2 (NS2)",
    dnsNs3: "DNS Server 3 (optional)", dnsNs4: "DNS Server 4 (optional)",
    saveDns: "Save DNS", dnsInstructions: "Instructions",
    dnsStep1: "1. Log in to your registrar (GoDaddy, Namecheap, OVH...)",
    dnsStep2: "2. Go to the DNS management of your domain",
    dnsStep3: "3. Replace existing NS with the ones above",
    dnsStep4: "4. Propagation takes 24-48h",
    copyDns: "Copy", dnsCopied: "Copied ✓",
    logoTitle: "Site logo", logoUpload: "Change logo", logoRemove: "Remove",
    logoHint: "Click to add a logo",
    siteNameLabel: "Site name", siteNamePlaceholder: "Your site name...",
    configureStripe: "Configure Stripe", configurePaypal: "Configure PayPal",
    newPage: "New page", keepOnePage: "Keep at least one page.",
    connectedError: "You must be logged in.", saveError: "Save error.",
    loadError: "Load error. Local data used.",
    paySuccess: "Payment successful!", payDone: "Your payment has been processed.",
    close: "Close", cancel: "Cancel", modifyAddress: "Modify address",
    cartTitle: "My cart", cartEmpty: "Your cart is empty", cartTotal: "Total",
    cartCheckout: "Checkout", cartRemove: "Remove",
    cartContinue: "Continue", cartAdd: "Add to cart",
    siteUrlLabel: "Your site URL",
    publishNoteFile: "The publier.txt file has been downloaded with all details.",
    sHero: "Title + CTA", sText: "Free paragraph", sImage: "Photo / illustration",
    sGallery: "Image grid", sVideo: "YouTube / Vimeo", sProducts: "Catalog",
    sFeatures: "Features grid", sPayment: "Stripe & PayPal", sForm: "Form", sDivider: "Decorative line",
    heroTitlePh: "Main title...", heroSubPh: "Subtitle...", heroCtaPh: "CTA Button...",
    textPh: "Your text here...",
    imgUploadHint: "Click to upload an image", imgChange: "Change", imgAltPh: "Alt text...",
    galleryLabel: "Gallery", galleryImages: "image(s)", galleryAdd: "+ Add",
    galleryEmpty: "No images — click \"+ Add\"",
    videoLabel: "Video", videoTitlePh: "Video title...", videoUrlPh: "YouTube or Vimeo URL...",
    videoHint: "Paste a YouTube or Vimeo URL",
    productsLabel: "Product catalog", addProduct: "+ Product",
    badgePh: "Badge (New, Sale...)", productNamePh: "Product name",
    productDescPh: "Short description", productPricePh: "Price",
    featureTitlePh: "Title...", featureDescPh: "Description...",
    paymentLabel: "Payment Section", paymentTitlePh: "Payment title...",
    paymentDescPh: "Description...", paymentAmountPh: "Amount",
    testStripe: "💳 Test Stripe", testPaypal: "🅿 Test PayPal",
    contactLabel: "Contact Form", namePh: "Full name", emailPh: "Email address",
    msgPh: "Your message...", sendBtn: "Send →",
    fontDefault: "Default", fontGeorgia: "Georgia", fontCourier: "Courier New",
    fontTrebuchet: "Trebuchet", fontVerdana: "Verdana",
    colOption2: "2 columns", colOption3: "3 columns", colOption4: "4 columns",
    buy: "🛒 Buy", login: "🔑 Sign in", logout: "Sign out",
    cart: "My cart", delivery: "Delivery & Payment", checkout: "Place order",
    back: "← Back", payCard: "💳 Pay by card",
    name: "Full name *", email: "Email *",
    password: "Password * (min.6)", confirm: "Confirm *",
    createAccount: "✨ Create account", register: "Register",
    send: "Send", noOrders: "No orders yet.",
    discover: "Discover products →", orders: "MY ORDERS",
    totalSpent: "TOTAL SPENT", forgotPwd: "Forgot password?",
    resetSent: "Email sent!", address: "Address", zip: "Zip code",
    city: "City", country: "Country",
    formTitle: "Contact Us",
    formNamePh: "Full name", formEmailPh: "Email", formMsgPh: "Your message...",
    formSend: "Send →", formSending: "Sending...",
    formSuccess: "✅ Message sent! We'll get back to you soon.",
    formErrRequired: "Please fill in all fields.",
    formErrEmail: "Invalid email.",
    formErrSend: "Send error. Please try again later.",
    checkoutClient: "👤 Customer info", checkoutDelivery: "📦 Delivery address",
    checkoutSecure: "🔒 Secure payment via Stripe",
    checkoutPaying: "Redirecting to Stripe...",
    loginTab: "Login", registerTab: "Register",
    loginBtn: "🔑 Sign in", createBtn: "✨ Create account",
    forgotDesc: "Enter your email to receive a reset link.",
    forgotSendBtn: "📧 Send link",
    storeClient: "🛍 Store customer", signOut: "⏻ Sign out",
    payWithStripe: "💳 Pay with Stripe", payWithPaypal: "🅿 Pay with PayPal",
  },

  es: {
    save: "Guardar", saving: "Guardando...", notConnected: "No conectado",
    saved: "✓ Guardado", unsaved: "● No guardado",
    edit: "✏ Editar", preview: "▶ Vista previa",
    sections: "Secciones", style: "Estilo",
    addSection: "Añadir una sección",
    properties: "Propiedades", typography: "Tipografía",
    textColor: "Color de texto", sectionBg: "Fondo de sección",
    fontSize: "Tamaño de fuente", auto: "Auto",
    small: "Pequeño", normal: "Normal", large: "Grande", xlarge: "Muy grande",
    pageStyle: "Estilo de página", bgColor: "Color de fondo",
    textColorPage: "Color de texto", font: "Fuente",
    columns: "Columnas", emptyPage: "Esta página está vacía.",
    addSectionHint: "Añade una sección desde el panel izquierdo.",
    export: "Exportar", exportTitle: "Exportar sitio",
    exportDesc: "Elige tu formato de exportación",
    htmlStatic: "HTML estático", htmlDesc: "Un archivo .html todo-en-uno, listo para alojar.",
    download: "Descargar", dlDesc: "Descarga tu sitio completo.",
    exportNote: "Las imágenes están integradas en base64. Los pagos Stripe/PayPal requieren un backend.",
    recommended: "Recomendado", exportSuccess: "Sitio exportado en HTML ✓",
    publish: "Publicar", publishTitle: "Publicar su sitio",
    publishDesc: "Elija una dirección para su sitio",
    siteAddress: "Dirección del sitio", siteAddressPlaceholder: "mi-sitio (ej: mi-tienda)",
    domainLink: "Vincular un dominio (opcional)", domainPlaceholder: "ej: www.midominio.com",
    publishBtn: "Publicar sitio", publishSuccess: "Sitio publicado ✓",
    dnsTitle: "Configuración DNS", dnsDesc: "Añade estos registros en tu registrador:",
    dnsInputTitle: "Introducir DNS personalizados", dnsInputDesc: "Introduce los servidores DNS de tu registrador (ej. GoDaddy, Namecheap...)",
    dnsNs1: "Servidor DNS 1 (NS1)", dnsNs2: "Servidor DNS 2 (NS2)",
    dnsNs3: "Servidor DNS 3 (opcional)", dnsNs4: "Servidor DNS 4 (opcional)",
    saveDns: "Guardar DNS", dnsInstructions: "Instrucciones",
    dnsStep1: "1. Inicia sesión en tu registrador (GoDaddy, Namecheap, OVH...)",
    dnsStep2: "2. Ve a la gestión DNS de tu dominio",
    dnsStep3: "3. Reemplaza los NS existentes por los de arriba",
    dnsStep4: "4. La propagación tarda 24-48h",
    copyDns: "Copiar", dnsCopied: "Copiado ✓",
    logoTitle: "Logo del sitio", logoUpload: "Cambiar logo", logoRemove: "Eliminar",
    logoHint: "Haz clic para añadir un logo",
    siteNameLabel: "Nombre del sitio", siteNamePlaceholder: "Nombre de tu sitio...",
    configureStripe: "Configurar Stripe", configurePaypal: "Configurar PayPal",
    newPage: "Nueva página", keepOnePage: "Mantén al menos una página.",
    connectedError: "Debes estar conectado.", saveError: "Error al guardar.",
    loadError: "Error de carga. Datos locales usados.",
    paySuccess: "¡Pago exitoso!", payDone: "Tu pago ha sido procesado.",
    close: "Cerrar", cancel: "Cancelar", modifyAddress: "Modificar dirección",
    cartTitle: "Mi carrito", cartEmpty: "Tu carrito está vacío", cartTotal: "Total",
    cartCheckout: "Finalizar pedido", cartRemove: "Eliminar",
    cartContinue: "Continuar", cartAdd: "Añadir al carrito",
    siteUrlLabel: "URL de tu sitio",
    publishNoteFile: "El archivo publier.txt fue descargado con todos los detalles.",
    sHero: "Título + CTA", sText: "Párrafo libre", sImage: "Foto / ilustración",
    sGallery: "Cuadrícula de imágenes", sVideo: "YouTube / Vimeo", sProducts: "Catálogo",
    sFeatures: "Cuadrícula de ventajas", sPayment: "Stripe & PayPal", sForm: "Formulario", sDivider: "Línea decorativa",
    heroTitlePh: "Título principal...", heroSubPh: "Subtítulo...", heroCtaPh: "Botón CTA...",
    textPh: "Tu texto aquí...",
    imgUploadHint: "Haz clic para cargar una imagen", imgChange: "Cambiar", imgAltPh: "Texto alt...",
    galleryLabel: "Galería", galleryImages: "imagen(es)", galleryAdd: "+ Añadir",
    galleryEmpty: "Sin imágenes — haz clic en \"+ Añadir\"",
    videoLabel: "Vídeo", videoTitlePh: "Título del vídeo...", videoUrlPh: "URL de YouTube o Vimeo...",
    videoHint: "Pega una URL de YouTube o Vimeo",
    productsLabel: "Catálogo de productos", addProduct: "+ Producto",
    badgePh: "Etiqueta (Nuevo, Oferta...)", productNamePh: "Nombre del producto",
    productDescPh: "Descripción corta", productPricePh: "Precio",
    featureTitlePh: "Título...", featureDescPh: "Descripción...",
    paymentLabel: "Sección de Pago", paymentTitlePh: "Título del pago...",
    paymentDescPh: "Descripción...", paymentAmountPh: "Importe",
    testStripe: "💳 Probar Stripe", testPaypal: "🅿 Probar PayPal",
    contactLabel: "Formulario de contacto", namePh: "Nombre completo", emailPh: "Correo electrónico",
    msgPh: "Tu mensaje...", sendBtn: "Enviar →",
    fontDefault: "Por defecto", fontGeorgia: "Georgia", fontCourier: "Courier New",
    fontTrebuchet: "Trebuchet", fontVerdana: "Verdana",
    colOption2: "2 columnas", colOption3: "3 columnas", colOption4: "4 columnas",
    buy: "🛒 Comprar", login: "🔑 Entrar", logout: "Salir",
    cart: "Mi carrito", delivery: "Entrega y Pago", checkout: "Finalizar pedido",
    back: "← Volver", payCard: "💳 Pagar con tarjeta",
    name: "Nombre completo *", email: "Email *",
    password: "Contraseña * (mín.6)", confirm: "Confirmar *",
    createAccount: "✨ Crear cuenta", register: "Registro",
    send: "Enviar", noOrders: "Sin pedidos por ahora.",
    discover: "Descubrir productos →", orders: "MIS PEDIDOS",
    totalSpent: "TOTAL GASTADO", forgotPwd: "¿Olvidaste tu contraseña?",
    resetSent: "¡Email enviado!", address: "Dirección", zip: "Código postal",
    city: "Ciudad", country: "País",
    formTitle: "Contáctenos",
    formNamePh: "Nombre completo", formEmailPh: "Email", formMsgPh: "Tu mensaje...",
    formSend: "Enviar →", formSending: "Enviando...",
    formSuccess: "✅ ¡Mensaje enviado! Te responderemos pronto.",
    formErrRequired: "Por favor, rellena todos los campos.",
    formErrEmail: "Email inválido.",
    formErrSend: "Error de envío. Inténtalo más tarde.",
    checkoutClient: "👤 Información del cliente", checkoutDelivery: "📦 Dirección de entrega",
    checkoutSecure: "🔒 Pago seguro via Stripe",
    checkoutPaying: "Redirigiendo a Stripe...",
    loginTab: "Iniciar sesión", registerTab: "Registro",
    loginBtn: "🔑 Entrar", createBtn: "✨ Crear cuenta",
    forgotDesc: "Introduce tu email para recibir un enlace.",
    forgotSendBtn: "📧 Enviar enlace",
    storeClient: "🛍 Cliente de la tienda", signOut: "⏻ Cerrar sesión",
    payWithStripe: "💳 Pagar con Stripe", payWithPaypal: "🅿 Pagar con PayPal",
  },

  ar: {
    save: "حفظ", saving: "جارٍ الحفظ...", notConnected: "غير متصل",
    saved: "✓ تم الحفظ", unsaved: "● غير محفوظ",
    edit: "✏ تحرير", preview: "▶ معاينة",
    sections: "الأقسام", style: "النمط",
    addSection: "إضافة قسم",
    properties: "الخصائص", typography: "الخط",
    textColor: "لون النص", sectionBg: "خلفية القسم",
    fontSize: "حجم الخط", auto: "تلقائي",
    small: "صغير", normal: "عادي", large: "كبير", xlarge: "كبير جداً",
    pageStyle: "نمط الصفحة", bgColor: "لون الخلفية",
    textColorPage: "لون النص", font: "الخط",
    columns: "الأعمدة", emptyPage: "هذه الصفحة فارغة.",
    addSectionHint: "أضف قسماً من اللوحة اليسرى.",
    export: "تصدير", exportTitle: "تصدير الموقع",
    exportDesc: "اختر تنسيق التصدير",
    htmlStatic: "HTML ثابت", htmlDesc: "ملف .html واحد جاهز للاستضافة.",
    download: "تحميل", dlDesc: "حمّل موقعك الكامل.",
    exportNote: "الصور مدمجة بصيغة base64. مدفوعات Stripe/PayPal تتطلب خادماً خلفياً.",
    recommended: "موصى به", exportSuccess: "تم تصدير الموقع ✓",
    publish: "نشر", publishTitle: "نشر موقعك",
    publishDesc: "اختر عنواناً لموقعك",
    siteAddress: "عنوان الموقع", siteAddressPlaceholder: "موقعي (مثال: متجري)",
    domainLink: "ربط اسم نطاق (اختياري)", domainPlaceholder: "مثال: www.نطاقي.com",
    publishBtn: "نشر الموقع", publishSuccess: "تم نشر الموقع ✓",
    dnsTitle: "إعداد DNS", dnsDesc: "أضف هذه السجلات لدى المسجّل:",
    dnsInputTitle: "إدخال DNS المخصص", dnsInputDesc: "أدخل خوادم DNS من مزود النطاق الخاص بك (GoDaddy, Namecheap...)",
    dnsNs1: "خادم DNS 1 (NS1)", dnsNs2: "خادم DNS 2 (NS2)",
    dnsNs3: "خادم DNS 3 (اختياري)", dnsNs4: "خادم DNS 4 (اختياري)",
    saveDns: "حفظ DNS", dnsInstructions: "تعليمات",
    dnsStep1: "1. سجّل الدخول إلى مزود النطاق (GoDaddy, Namecheap, OVH...)",
    dnsStep2: "2. انتقل إلى إدارة DNS للنطاق",
    dnsStep3: "3. استبدل NS الحالية بالخوادم أعلاه",
    dnsStep4: "4. قد يستغرق الانتشار 24-48 ساعة",
    copyDns: "نسخ", dnsCopied: "تم النسخ ✓",
    logoTitle: "شعار الموقع", logoUpload: "تغيير الشعار", logoRemove: "حذف",
    logoHint: "انقر لإضافة شعار",
    siteNameLabel: "اسم الموقع", siteNamePlaceholder: "اسم موقعك...",
    configureStripe: "إعداد Stripe", configurePaypal: "إعداد PayPal",
    newPage: "صفحة جديدة", keepOnePage: "احتفظ بصفحة واحدة على الأقل.",
    connectedError: "يجب أن تكون متصلاً.", saveError: "خطأ في الحفظ.",
    loadError: "خطأ في التحميل. تم استخدام البيانات المحلية.",
    paySuccess: "تم الدفع بنجاح!", payDone: "تمت معالجة دفعتك.",
    close: "إغلاق", cancel: "إلغاء", modifyAddress: "تعديل العنوان",
    cartTitle: "سلة التسوق", cartEmpty: "سلتك فارغة", cartTotal: "المجموع",
    cartCheckout: "إتمام الطلب", cartRemove: "حذف",
    cartContinue: "متابعة", cartAdd: "أضف إلى السلة",
    siteUrlLabel: "رابط موقعك",
    publishNoteFile: "تم تحميل ملف publier.txt مع جميع التفاصيل.",
    sHero: "عنوان + CTA", sText: "فقرة حرة", sImage: "صورة / رسم",
    sGallery: "شبكة صور", sVideo: "يوتيوب / فيميو", sProducts: "كتالوج",
    sFeatures: "شبكة مميزات", sPayment: "Stripe & PayPal", sForm: "نموذج", sDivider: "فاصل زخرفي",
    heroTitlePh: "العنوان الرئيسي...", heroSubPh: "العنوان الفرعي...", heroCtaPh: "زر CTA...",
    textPh: "نصك هنا...",
    imgUploadHint: "انقر لتحميل صورة", imgChange: "تغيير", imgAltPh: "نص بديل...",
    galleryLabel: "معرض", galleryImages: "صورة/صور", galleryAdd: "+ إضافة",
    galleryEmpty: "لا توجد صور — انقر على \"+ إضافة\"",
    videoLabel: "فيديو", videoTitlePh: "عنوان الفيديو...", videoUrlPh: "رابط يوتيوب أو فيميو...",
    videoHint: "الصق رابط يوتيوب أو فيميو",
    productsLabel: "كتالوج المنتجات", addProduct: "+ منتج",
    badgePh: "شارة (جديد، عرض...)", productNamePh: "اسم المنتج",
    productDescPh: "وصف قصير", productPricePh: "السعر",
    featureTitlePh: "العنوان...", featureDescPh: "الوصف...",
    paymentLabel: "قسم الدفع", paymentTitlePh: "عنوان الدفع...",
    paymentDescPh: "الوصف...", paymentAmountPh: "المبلغ",
    testStripe: "💳 اختبار Stripe", testPaypal: "🅿 اختبار PayPal",
    contactLabel: "نموذج الاتصال", namePh: "الاسم الكامل", emailPh: "البريد الإلكتروني",
    msgPh: "رسالتك...", sendBtn: "إرسال →",
    fontDefault: "افتراضي", fontGeorgia: "Georgia", fontCourier: "Courier New",
    fontTrebuchet: "Trebuchet", fontVerdana: "Verdana",
    colOption2: "عمودان", colOption3: "3 أعمدة", colOption4: "4 أعمدة",
    buy: "🛒 شراء", login: "🔑 دخول", logout: "خروج",
    cart: "سلتي", delivery: "التسليم والدفع", checkout: "إتمام الطلب",
    back: "→ رجوع", payCard: "💳 الدفع ببطاقة",
    name: "الاسم الكامل *", email: "البريد الإلكتروني *",
    password: "كلمة المرور * (6 أحرف)", confirm: "تأكيد *",
    createAccount: "✨ إنشاء حساب", register: "تسجيل",
    send: "إرسال", noOrders: "لا توجد طلبات حتى الآن.",
    discover: "اكتشف المنتجات ←", orders: "طلباتي",
    totalSpent: "الإجمالي المنفق", forgotPwd: "نسيت كلمة المرور؟",
    resetSent: "تم الإرسال!", address: "العنوان", zip: "الرمز البريدي",
    city: "المدينة", country: "البلد",
    formTitle: "اتصل بنا",
    formNamePh: "الاسم الكامل", formEmailPh: "البريد الإلكتروني", formMsgPh: "رسالتك...",
    formSend: "إرسال →", formSending: "جارٍ الإرسال...",
    formSuccess: "✅ تم إرسال الرسالة! سنرد عليك قريباً.",
    formErrRequired: "يرجى ملء جميع الحقول.",
    formErrEmail: "البريد الإلكتروني غير صالح.",
    formErrSend: "خطأ في الإرسال. حاول مرة أخرى لاحقاً.",
    checkoutClient: "👤 معلومات العميل", checkoutDelivery: "📦 عنوان التسليم",
    checkoutSecure: "🔒 دفع آمن عبر Stripe",
    checkoutPaying: "جارٍ التوجيه إلى Stripe...",
    loginTab: "تسجيل الدخول", registerTab: "إنشاء حساب",
    loginBtn: "🔑 دخول", createBtn: "✨ إنشاء حساب",
    forgotDesc: "أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين.",
    forgotSendBtn: "📧 إرسال الرابط",
    storeClient: "🛍 عميل المتجر", signOut: "⏻ تسجيل الخروج",
    payWithStripe: "💳 الدفع عبر Stripe", payWithPaypal: "🅿 الدفع عبر PayPal",
  },
}

// ── Helper : retourne les traductions pour une langue ─────────────
export const getT = (lang) => translations[lang] || translations.fr
